site_name: PaddleOCR 文档
site_url: https://zhang-prog.github.io/PaddleOCR/
site_author: PaddleOCR PMC
site_description:
  test1

repo_name: zhang-prog/PaddleOCR
repo_url: https://github.com/zhang-prog/PaddleOCR

copyright: Copyright &copy; 2024 Maintained by PaddleOCR PMC.

edit_uri: edit/main/docs/

theme:
  name: material
  logo: version2.x/static/images/logo.jpg
  favicon: version2.x/static/images/logo.jpg
  custom_dir: overrides
  features:
    - announce.dismiss
    - content.tooltips
    - content.code.copy
    - content.tabs.link
    - content.footnote.tooltips
    - content.action.edit
    - content.action.view
    - navigation.expand  # 默认打开所有的字节
    - navigation.tabs # 顶级索引被作为tab
    - navigation.tabs.sticky # tab始终可见
    - navigation.top # 开启顶部导航栏
    - navigation.tracking # 导航栏跟踪
    - navigation.footer
    - navigation.indexes
    - search.highlight # 搜索高亮
    - search.share # 搜索分享
    - search.suggest # 搜索建议
    - toc.follow # 目录跟踪-页面右侧的小目录

  palette:
    - media: "(prefers-color-scheme: light)" # 浅色
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)" # 深色
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

  icon:
    logo: logo
    previous: fontawesome/solid/angle-left
    next: fontawesome/solid/angle-right
    repo: fontawesome/brands/github
    edit: material/pencil
    view: material/eye
    tag:
      default-tag: fontawesome/solid/tag
      hardware-tag: fontawesome/solid/microchip
      software-tag: fontawesome/solid/laptop-code
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16

plugins:
  - tags
  - offline
  - search:
      separator: '[\s\u200b\-_,:!=\[\: )"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - i18n:
      docs_structure: suffix
      fallback_to_default: true
      reconfigure_material: true
      reconfigure_search: true
      languages:
        - locale: zh
          name: 简体中文
          default: true
          build: true
        - locale: en
          name: English
          site_name: PaddleOCR Documentation
          link: /en/
          nav_translations:
            Home: Home
            快速开始: Quick Start
            近期更新: Recently Update
            低代码全流程开发: All-in-One Development
            概述: Overview
            模型: Model
            PP-OCR 文本检测识别: PP-OCR
            快速安装: Quick Installation
            效果展示: Visualization
            运行环境: Environment Preparation
            模型库: Model
            模型训练: Model Training
            基本概念: Basic concepts
            文本检测: Text Detection
            文本识别: Text Recognition
            文本方向分类器: Text Angle Classification
            关键信息提取: Key Information Extraction
            模型微调: Fine-tune
            训练tricks: Training Tricks
            模型压缩: Model Compression
            模型量化: Model Quantization
            模型裁剪: Model Prune
            知识蒸馏: Knowledge Distillation
            推理部署: Model Deploy
            基于Python预测引擎推理: Python Inference
            基于C++预测引擎推理: CPP Inference
            Visual Studio 2019 Community CMake 编译指南: Visual Studio 2019 Community CMake Compilation Guide
            服务化部署: Sever Deployment
            端侧部署: Device-side Deployment
            Paddle2ONNX模型转化与预测: Paddle2ONNX
            云上飞桨部署工具: Paddle Cloud
            Benchmark: Benchmark
            博客: Blog
            paddleocr package使用说明: Paddleocr Package Instructions
            多语言模型: Multi-language model
            动手学OCR: Dive into OCR
            切片操作: Slice
            PaddleOCR模型推理参数解释: PaddleOCR Model Inference Parameter Explanation
            分布式训练: Distributed training
            项目克隆: Project Clone
            配置文件内容与生成: Configuration
            如何生产自定义超轻量模型？: How To Make Your own lightweight OCR model?
            PP-Structure文档分析: PP-Structure
            版面分析: Layout Analysis
            版面恢复: Recovery To Doc
            表格识别: Table Recognition
            返回识别位置: Return Recognition Location
            怎样完成基于图像数据的信息抽取任务: Key Information Extraction Pipeline
            前沿算法与模型: Academic Algorithms
            文本检测算法: Text Detection Algorithms
            DB与DB++: DB and DB++
            文本识别算法: Text Recognition Algorithms
            文本超分辨率算法: Text Super-Resolution Algorithm
            公式识别算法: Formulat Recognition
            端到端OCR算法: End-to-End OCR Algorithms
            表格识别算法: Table Recognition Algorithms
            关键信息抽取算法: Key Information Extraction Algorithms
            使用PaddleOCR架构添加新算法: Add new algorithms
            场景应用: Applications
            数据标注与合成: Data Annotation and Synthesis
            其它数据标注工具: Other data annotation tools
            其它数据合成工具: Others data synthesis tools
            数据集: Datasets
            通用中英文OCR数据集: General Chinese and English OCR dataset
            手写中文OCR数据集: Handwritten Chinese OCR Dataset
            垂类多语言OCR数据集: Vertical multi-language OCR dataset
            版面分析数据集: Layout Analysis Dataset
            表格识别数据集: Table recognition dataset
            关键信息提取数据集: Key Information Extraction Dataset
            FAQ: FAQ
            社区: Community
            社区贡献: Community Contribution
            附录: Appendix
        - locale: ja
          name: 日本語
          site_name: PaddleOCR ドキュメント
          link: /ja/
          nav_translations:
            Home: トップページ
        - locale: ru
          name: Pу́сский язы́к
          site_name: Документация PaddleOCR
          link: /ru/
          nav_translations:
            Home: Главная страница
        - locale: hi
          name: हिन्दी
          site_name: पैडलओसीआर दस्तावेज़ीकरण
          link: /hi/
          nav_translations:
            Home: घर पृष्ठ
        - locale: ko
          name: 한국인
          site_name: PaddleOCR 문서
          link: /ko/
          nav_translations:
            Home: 첫 페이지
        - locale: "null"
          name: Help translating
          build: false
          fixed_link: "https://github.com/PaddlePaddle/PaddleOCR/discussions/13374"
  - git-committers:
      repository: PaddlePaddle/PaddleOCR
      branch: main
      token: !!python/object/apply:os.getenv ["MKDOCS_GIT_COMMITTERS_APIKEY"]
  - git-revision-date-localized:
      fallback_to_build_date: false
      enable_creation_date: true

markdown_extensions:
  - abbr
  - attr_list
  - pymdownx.snippets
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - footnotes
  - def_list
  - md_in_html
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
        anchor_linenums: true
        line_spans: __span
        pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/PaddlePaddle/PaddleOCR
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/paddleocr/
  version:
    provider: mike

extra_javascript:
  - javascripts/katex.min.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js

extra_css:
  - https://unpkg.com/katex@0/dist/katex.min.css

nav:
  - Home: README.md
  - 快速开始: version3.x/quick_start.md
  - 近期更新: update/update.md 
  - 推理部署: 
    - 高性能推理: version3.x/deployment/high_performance_inference.md
    - 获取onnx模型: version3.x/deployment/obtaining_onnx_models.md
    - 端侧部署: version3.x/deployment/on_device_deployment.md
    - 服务化部署: version3.x/deployment/serving.md
  - PP-OCRv5: version3.x/pipeline_usage/OCR.md
  - PP-StructureV3: version3.x/pipeline_usage/PP-StructureV3.md
  - PP-ChatOCRv4: version3.x/pipeline_usage/PP-ChatOCRv4.md
  - 模块列表: 
    - 文档图像方向分类模块: version3.x/module_usage/doc_img_orientation_classification.md
    - 文档类视觉语言模型模块: version3.x/module_usage/doc_vlm.md
    - 公式识别模块: version3.x/module_usage/formula_recognition.md
    - 版面区域检测模块: version3.x/module_usage/layout_detection.md
    - 印章文本检测模块: version3.x/module_usage/seal_text_detection.md
    - 表格单元格检测模块: version3.x/module_usage/table_cells_detection.md
    - 表格分类模块: version3.x/module_usage/table_classification.md
    - 表格结构识别模块: version3.x/module_usage/table_structure_recognition.md
    - 文本检测模块: version3.x/module_usage/text_detection.md
    - 文本图像矫正模块: version3.x/module_usage/text_image_unwarping.md
    - 文本行方向分类模块: version3.x/module_usage/text_line_orientation_classification.md
    - 文本识别模块: version3.x/module_usage/text_recognition.md
  - 产线列表: 
    - 公式识别产线: version3.x/pipeline_usage/formula_recognition.md
    - 文档图像预处理产线: version3.x/pipeline_usage/doc_preprocessor.md
    - 文档理解产线: version3.x/pipeline_usage/doc_understanding.md
    - 印章文本识别产线: version3.x/pipeline_usage/seal_recognition.md
    - 通用表格识别v2产线: version3.x/pipeline_usage/table_recognition_v2.md
  - 低代码全流程开发:
      - 概述: version3.x/paddlex/overview.md
      - 快速开始: version3.x/paddlex/quick_start.md
  - 数据标注与合成&数据集:
    - 概述: data_anno_synth/overview.md
    - 其它数据标注工具: data_anno_synth/data_annotation.md
    - 其它数据合成工具: data_anno_synth/data_synthesis.md
    - 通用中英文OCR数据集: datasets/datasets.md
    - 手写中文OCR数据集: datasets/handwritten_datasets.md
    - 垂类多语言OCR数据集: datasets/vertical_and_multilingual_datasets.md
    - 版面分析数据集: datasets/layout_datasets.md
    - 表格识别数据集: datasets/table_datasets.md
    - 关键信息提取数据集: datasets/kie_datasets.md
  - version2.x:
    - 概述: version2.x/legacy/index.md
    - 模型列表: version2.x/legacy/model_list.md
    - 基于Python预测引擎推理: version2.x/legacy/python_infer.md
    - 基于C++预测引擎推理: version2.x/legacy/cpp_infer.md
    - Visual Studio 2019 Community CMake 编译指南: version2.x/legacy/windows_vs2019_build.md
    - 服务化部署: version2.x/legacy/paddle_server.md
    - Android部署: version2.x/legacy/android_demo.md
    - 端侧部署: version2.x/legacy/lite.md
    - Paddle2ONNX模型转化与预测: version2.x/legacy/paddle2onnx.md
    - 云上飞桨部署工具: version2.x/legacy/paddle_cloud.md
    - Benchmark: version2.x/legacy/benchmark.md
  - FAQ: FAQ.md
  - 社区:
    - 社区贡献: community/community_contribution.md
    - 附录: community/code_and_doc.md
